import { Patient, Appointment } from '../types';

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'p-001',
    patient_id: 'PT-1001',
    full_name: 'Eleanor Vance',
    date_of_birth: '1988-04-12',
    age: 38,
    gender: 'Female',
    blood_group: 'O+',
    phone: '+1 (555) 234-5678',
    email: 'eleanor.vance@example.com',
    address: '742 Evergreen Terrace, Springfield, OR',
    emergency_contact: 'Mark Vance (Spouse) - +1 (555) 987-6543',
    medical_condition: 'Type 2 Diabetes, Mild Hypertension',
    registration_date: '2025-01-14',
    notes: 'Monitors blood glucose daily. Allergic to penicillin.',
    created_at: '2025-01-14T09:30:00Z',
  },
  {
    id: 'p-002',
    patient_id: 'PT-1002',
    full_name: 'Marcus Thorne',
    date_of_birth: '1995-11-23',
    age: 30,
    gender: 'Male',
    blood_group: 'A+',
    phone: '+1 (555) 345-6789',
    email: 'marcus.thorne@example.com',
    address: '128 Willow Creek Way, Austin, TX',
    emergency_contact: 'Sarah Thorne (Sister) - +1 (555) 876-5432',
    medical_condition: 'Asthma (Exercise-induced)',
    registration_date: '2025-02-03',
    notes: 'Uses Albuterol inhaler before physical exercise.',
    created_at: '2025-02-03T11:15:00Z',
  },
  {
    id: 'p-003',
    patient_id: 'PT-1003',
    full_name: 'Dr. Sophia Reyes',
    date_of_birth: '1974-08-19',
    age: 52,
    gender: 'Female',
    blood_group: 'B-',
    phone: '+1 (555) 456-7890',
    email: 'sophia.reyes@example.com',
    address: '405 Harbor View Blvd, Seattle, WA',
    emergency_contact: 'Carlos Reyes (Husband) - +1 (555) 765-4321',
    medical_condition: 'Chronic Migraines, Hypothyroidism',
    registration_date: '2025-02-18',
    notes: 'Prescribed levothyroxine 50mcg daily in morning.',
    created_at: '2025-02-18T14:20:00Z',
  },
  {
    id: 'p-004',
    patient_id: 'PT-1004',
    full_name: 'David K. Miller',
    date_of_birth: '1962-03-05',
    age: 64,
    gender: 'Male',
    blood_group: 'AB+',
    phone: '+1 (555) 567-8901',
    email: 'david.miller@example.com',
    address: '89 Oakridge Avenue, Denver, CO',
    emergency_contact: 'Claire Miller (Daughter) - +1 (555) 654-3210',
    medical_condition: 'Coronary Artery Disease, Hyperlipidemia',
    registration_date: '2025-03-01',
    notes: 'Post-stent follow up needed every 6 months. Statin therapy.',
    created_at: '2025-03-01T10:00:00Z',
  },
  {
    id: 'p-005',
    patient_id: 'PT-1005',
    full_name: 'Amara Okafor',
    date_of_birth: '2001-09-30',
    age: 24,
    gender: 'Female',
    blood_group: 'O-',
    phone: '+1 (555) 678-9012',
    email: 'amara.okafor@example.com',
    address: '15 Magnolia Court, Atlanta, GA',
    emergency_contact: 'Chidi Okafor (Father) - +1 (555) 543-2109',
    medical_condition: 'Seasonal Allergic Rhinitis, Eczema',
    registration_date: '2025-03-10',
    notes: 'Responds well to cetirizine. Topical hydrocortisone for flare-ups.',
    created_at: '2025-03-10T16:45:00Z',
  },
  {
    id: 'p-006',
    patient_id: 'PT-1006',
    full_name: 'James L. Sullivan',
    date_of_birth: '1981-07-14',
    age: 45,
    gender: 'Male',
    blood_group: 'A-',
    phone: '+1 (555) 789-0123',
    email: 'james.sullivan@example.com',
    address: '312 Beacon Hill Road, Boston, MA',
    emergency_contact: 'Emily Sullivan (Spouse) - +1 (555) 432-1098',
    medical_condition: 'Lumbar Disc Herniation, Sciatica',
    registration_date: '2025-03-12',
    notes: 'Physical therapy ongoing twice per week.',
    created_at: '2025-03-12T08:15:00Z',
  },
];

// Helper to generate dynamic dates around today for realistic demonstration
const todayStr = new Date().toISOString().split('T')[0];

const getRelativeDate = (daysOffset: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString().split('T')[0];
};

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-001',
    appointment_id: 'APT-2001',
    patient_id: 'p-001',
    doctor: 'Dr. Sarah Jenkins (Endocrinology)',
    appointment_date: todayStr,
    appointment_time: '09:30',
    reason_for_visit: 'Quarterly HbA1c review and insulin dosage adjustments',
    status: 'Scheduled',
    notes: 'Bring current glucose log book.',
    created_at: '2025-03-10T09:00:00Z',
  },
  {
    id: 'apt-002',
    appointment_id: 'APT-2002',
    patient_id: 'p-004',
    doctor: 'Dr. Robert Taylor (Cardiology)',
    appointment_date: todayStr,
    appointment_time: '11:00',
    reason_for_visit: 'Post-stent 6-month echocardiogram and lipid profile assessment',
    status: 'Completed',
    notes: 'Vital signs stable. Ejection fraction normal.',
    created_at: '2025-03-08T14:30:00Z',
  },
  {
    id: 'apt-003',
    appointment_id: 'APT-2003',
    patient_id: 'p-002',
    doctor: 'Dr. Michael Chen (Pulmonology)',
    appointment_date: todayStr,
    appointment_time: '14:15',
    reason_for_visit: 'Spirometry test and seasonal asthma flare-up assessment',
    status: 'Scheduled',
    notes: 'Patient reported nighttime coughing.',
    created_at: '2025-03-11T10:15:00Z',
  },
  {
    id: 'apt-004',
    appointment_id: 'APT-2004',
    patient_id: 'p-003',
    doctor: 'Dr. Emily Brooks (Neurology)',
    appointment_date: getRelativeDate(1),
    appointment_time: '10:00',
    reason_for_visit: 'Migraine frequency evaluation and prophylactic review',
    status: 'Scheduled',
    notes: 'Discuss CGRP inhibitors if headaches persist.',
    created_at: '2025-03-12T11:00:00Z',
  },
  {
    id: 'apt-005',
    appointment_id: 'APT-2005',
    patient_id: 'p-006',
    doctor: 'Dr. Robert Taylor (Orthopedics)',
    appointment_date: getRelativeDate(3),
    appointment_time: '15:30',
    reason_for_visit: 'MRI spine review and rehabilitation progress check',
    status: 'Scheduled',
    notes: 'Physical therapy report requested from clinic.',
    created_at: '2025-03-13T13:45:00Z',
  },
  {
    id: 'apt-006',
    appointment_id: 'APT-2006',
    patient_id: 'p-005',
    doctor: 'Dr. Michael Chen (Allergy & Immunology)',
    appointment_date: getRelativeDate(-2),
    appointment_time: '13:00',
    reason_for_visit: 'Skin prick allergy panel test',
    status: 'Completed',
    notes: 'Positive for oak and cedar pollen. Antihistamine prescribed.',
    created_at: '2025-03-05T09:20:00Z',
  },
  {
    id: 'apt-007',
    appointment_id: 'APT-2007',
    patient_id: 'p-001',
    doctor: 'Dr. Emily Brooks (Ophthalmology)',
    appointment_date: getRelativeDate(-5),
    appointment_time: '16:00',
    reason_for_visit: 'Annual diabetic retinal examination',
    status: 'Cancelled',
    notes: 'Patient rescheduled due to work emergency.',
    created_at: '2025-03-01T15:10:00Z',
  },
];

export const AVAILABLE_DOCTORS = [
  'Dr. Sarah Jenkins (Endocrinology)',
  'Dr. Michael Chen (Pulmonology & Allergy)',
  'Dr. Emily Brooks (Neurology & Internal Medicine)',
  'Dr. Robert Taylor (Cardiology)',
  'Dr. Lisa Patel (Pediatrics & Family Medicine)',
  'Dr. Marcus Wright (General Surgery & Orthopedics)',
];

export const BLOOD_GROUPS: import('../types').BloodGroup[] = [
  'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'
];
